[project]
name = "pose2d-animator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mediapipe>=0.10.21",
    "opencv-python>=4.11.0.86",
    "pygame>=2.6.1",
]

[dependency-groups]
dev = [
    "ruff>=0.11.13",
]
